'use client';
import Link from 'next/link';
import { BookOpen, Eye } from 'lucide-react';
import { useLanguage } from '@/context/LanguageContext';
import { DocumentItem } from './DocumentDetailsModal';

interface RecentKnowledgeBaseDocumentsProps {
  onSelectDocument: (doc: DocumentItem) => void;
}

export const mockDocuments: DocumentItem[] = [
  {
    id: 'kb-doc-001',
    title: 'YCOIN Sovereign AI & Bitcoin L2 Whitepaper v2.4',
    filename: 'YCOIN_Whitepaper_v2.4.pdf',
    format: 'PDF',
    chars: '1,120 chars',
    size: '239.3 KB',
    uploadedBy: 'admin@ycoin.ai',
    content: `YCOIN ($Y) Sovereign AI & Bitcoin L2 Protocol Specification

1. EXECUTIVE SUMMARY:
YCOIN is the first sovereign AI-driven Layer-2 Intelligence protocol natively anchored to Bitcoin's immutable Proof-of-Work (PoW) consensus. By combining BitVM zero-knowledge state verifiers with autonomous AI agent runtimes, YCOIN enables high-frequency private AI computation directly backed by Bitcoin security.

2. ARCHITECTURAL PILLARS:
- Bitcoin Hash Anchoring: Every state root generated by YCOIN AI agents is committed into Bitcoin L1 taproot transactions every 10 blocks.
- BitVM ZK Verification: Fraud-proof mechanisms allow non-interactive verification of complex AI neural network inferences on Bitcoin without requiring hard forks.
- Sovereign Consensus: Decentralized node operators stake $Y and provide GPU compute power to run LLM inference nodes.`,
  },
  {
    id: 'kb-doc-002',
    title: 'PoW Block Subsidy & AI Node Staking Mech',
    filename: 'PoW_Node_Staking_Guide.docx',
    format: 'WORD',
    chars: '610 chars',
    size: '142.8 KB',
    uploadedBy: 'admin@ycoin.ai',
    content: `PoW Block Subsidy & AI Node Staking Mechanisms

Overview of Staking Dynamics:
Node operators must lock a minimum of 10,000 $Y tokens to operate a verified AI inference node. Staking rewards are calculated per epoch based on GPU uptime, latency SLA compliance, and zero-knowledge proof generation speed.

Slashing Conditions:
1. Malicious inference payload generation
2. Uptime below 99.2% per billing cycle
3. Failure to submit BitVM validity proofs within the required challenge period.`,
  },
  {
    id: 'kb-doc-003',
    title: 'BitVM Zero-Knowledge Bridge Security Guid',
    filename: 'BitVM_Bridge_Security.md',
    format: 'MD',
    chars: '540 chars',
    size: '88.5 KB',
    uploadedBy: 'admin@ycoin.ai',
    content: `BitVM Zero-Knowledge Bridge Security Guidelines

Security Directives:
- Ensure all taproot script trees are generated using verified tapleaf hashes.
- Optimistic execution requires 2-of-2 multisig signatories to monitor state roots 24/7.
- Emergency pause triggers require a 3-of-5 admin key consensus in case of protocol anomaly detection.`,
  },
];

const formatBadgeStyle = (format: string) => {
  switch (format) {
    case 'PDF':
      return 'bg-rose-500/15 border-rose-500/30 text-rose-400';
    case 'WORD':
      return 'bg-blue-500/15 border-blue-500/30 text-blue-400';
    case 'MD':
      return 'bg-emerald-500/15 border-emerald-500/30 text-emerald-400';
    default:
      return 'bg-gray-500/15 border-gray-500/30 text-gray-400';
  }
};

const RecentKnowledgeBaseDocuments = ({
  onSelectDocument,
}: RecentKnowledgeBaseDocumentsProps) => {
  const { t } = useLanguage();

  return (
    <div className="bg-[#0A101D] border border-border-color rounded-2xl p-6 shadow-sm flex flex-col justify-between h-full">
      <div>
        {/* Card Title & Link */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-[#0071E3]" />
            <h2 className="text-sm font-bold text-white tracking-tight">
              {t.recentKbDocs}
            </h2>
          </div>
          <Link
            href="/knowledge-base"
            className="text-xs text-[#0071E3] hover:underline font-medium"
          >
            {t.viewAll}
          </Link>
        </div>

        {/* Documents List */}
        <div className="space-y-3">
          {mockDocuments.map((doc) => (
            <div
              key={doc.id}
              onClick={() => onSelectDocument(doc)}
              className="bg-[#040812] border border-border-color/80 hover:border-[#0071E3]/50 rounded-xl p-3.5 flex items-center justify-between gap-3 group transition-all cursor-pointer"
            >
              <div className="flex items-center gap-3 min-w-0">
                {/* Format Badge */}
                <div
                  className={`w-11 h-9 rounded-lg border flex items-center justify-center font-bold text-[10px] uppercase tracking-wider shrink-0 ${formatBadgeStyle(
                    doc.format
                  )}`}
                >
                  {doc.format}
                </div>

                {/* Info */}
                <div className="min-w-0">
                  <h4 className="text-xs font-semibold text-white truncate group-hover:text-[#0071E3] transition-colors">
                    {doc.title}
                  </h4>
                  <p className="text-[11px] text-description truncate mt-0.5">
                    {doc.filename} • {doc.chars}
                  </p>
                </div>
              </div>

              {/* Action Eye Icon */}
              <button
                type="button"
                onClick={(e) => {
                  e.stopPropagation();
                  onSelectDocument(doc);
                }}
                className="w-8 h-8 rounded-lg bg-[#111A2E] group-hover:bg-[#0071E3] border border-border-color group-hover:border-[#0071E3] flex items-center justify-center text-gray-400 group-hover:text-white transition-all shrink-0"
              >
                <Eye className="w-4 h-4" />
              </button>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default RecentKnowledgeBaseDocuments;