'use client';

import React, { useState } from 'react';
import { Database } from 'lucide-react';
import UploadNewKnowledgeDocument from '@/components/app/UploadNewKnowledgeDocument';
import IndexedKnowledgeDocuments, { IndexedDocumentItem } from '@/components/app/IndexedKnowledgeDocuments';
import DocumentDetailsModal, { DocumentItem } from '@/components/app/DocumentDetailsModal';
import { useLanguage } from '@/context/LanguageContext';

const initialKnowledgeDocuments: IndexedDocumentItem[] = [
  {
    id: 'kb-doc-001',
    title: 'YCOIN Sovereign AI & Bitcoin L2 Whitepaper v2.4',
    filename: 'YCOIN_Whitepaper_v2.4.pdf',
    format: 'PDF',
    size: '239.3 KB',
    chars: '1,120 chars',
    indexedDate: '2026-07-31T06:03:28.899Z',
    uploadedBy: 'admin@ycoin.ai',
    content: `YCOIN ($Y) Sovereign AI & Bitcoin L2 Protocol Specification

1. EXECUTIVE SUMMARY:
YCOIN is the first sovereign AI-driven Layer-2 Intelligence protocol natively anchored to Bitcoin's immutable Proof-of-Work (PoW) consensus. By combining BitVM zero-knowledge state verifiers with autonomous AI agent runtimes, YCOIN enables high-frequency private AI computation directly backed by Bitcoin security.

2. ARCHITECTURAL PILLARS:
- Bitcoin Hash Anchoring: Every state root generated by YCOIN AI agents is committed into Bitcoin L1 taproot transactions every 10 blocks.
- BitVM ZK Verification: Fraud-proof mechanisms allow non-interactive verification of complex AI neural network inferences on Bitcoin without requiring hard forks.
- Sovereign Consensus: Decentralized node operators stake $Y and provide GPU compute power to run LLM inference nodes.`,
  },
  {
    id: 'kb-doc-002',
    title: 'PoW Block Subsidy & AI Node Staking Mechanics',
    filename: 'PoW_Node_Staking_Guide.docx',
    format: 'WORD',
    size: '115.2 KB',
    chars: '610 chars',
    indexedDate: '2026-08-03T06:03:28.899Z',
    uploadedBy: 'admin@ycoin.ai',
    content: `PoW Block Subsidy & AI Node Staking Mechanics

Overview of Staking Dynamics:
Node operators must lock a minimum of 10,000 $Y tokens to operate a verified AI inference node. Staking rewards are calculated per epoch based on GPU uptime, latency SLA compliance, and zero-knowledge proof generation speed.

Slashing Conditions:
1. Malicious inference payload generation
2. Uptime below 99.2% per billing cycle
3. Failure to submit BitVM validity proofs within the required challenge period.`,
  },
  {
    id: 'kb-doc-003',
    title: 'BitVM Zero-Knowledge Bridge Security Guidelines',
    filename: 'BitVM_Bridge_Security.md',
    format: 'PDF',
    size: '41.0 KB',
    chars: '540 chars',
    indexedDate: '2026-08-04T22:03:28.899Z',
    uploadedBy: 'admin@ycoin.ai',
    content: `BitVM Zero-Knowledge Bridge Security Guidelines

Security Directives:
- Ensure all taproot script trees are generated using verified tapleaf hashes.
- Optimistic execution requires 2-of-2 multisig signatories to monitor state roots 24/7.
- Emergency pause triggers require a 3-of-5 admin key consensus in case of protocol anomaly detection.`,
  },
];

const KnowledgeBasePage = () => {
  const { t } = useLanguage();
  const [documents, setDocuments] = useState<IndexedDocumentItem[]>(initialKnowledgeDocuments);
  const [selectedDoc, setSelectedDoc] = useState<DocumentItem | null>(null);

  const handleAddDocument = (newDoc: DocumentItem) => {
    const docWithDate: IndexedDocumentItem = {
      ...newDoc,
      indexedDate: new Date().toISOString(),
    };
    setDocuments((prev) => [docWithDate, ...prev]);
  };

  const handleDeleteDocument = (docId: string) => {
    setDocuments((prev) => prev.filter((d) => d.id !== docId));
  };

  return (
    <div className="space-y-6 sm:space-y-8 animate-in fade-in duration-300">
      {/* Top Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <div className="w-8 h-8 rounded-xl bg-[#0071E3]/15 border border-[#0071E3]/30 flex items-center justify-center text-[#0071E3]">
              <Database className="w-4 h-4" />
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
              {t.aiKbManagementTitle}
            </h1>
          </div>
          <p className="text-xs sm:text-sm text-description max-w-3xl leading-relaxed">
            {t.aiKbManagementDesc}
          </p>
        </div>
      </div>

      {/* Top Card: Upload Form */}
      <UploadNewKnowledgeDocument onAddDocument={handleAddDocument} />

      {/* Bottom Card: Indexed Documents Table */}
      <IndexedKnowledgeDocuments
        documents={documents}
        onSelectDocument={(doc) => setSelectedDoc(doc)}
        onDeleteDocument={handleDeleteDocument}
      />

      {/* Document Details Inspector Modal */}
      <DocumentDetailsModal
        document={selectedDoc}
        isOpen={!!selectedDoc}
        onClose={() => setSelectedDoc(null)}
      />
    </div>
  );
};

export default KnowledgeBasePage;